inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - node_modules
    - db/schema.rb
    - db/migrate/*
    - bin/*
