FROM ruby:3.1.0
RUN apt-get update -qq && apt-get install -y postgresql-client nodejs yarn

RUN groupadd -g 1000 hzyy && useradd -u 1000 -g hzyy -m hzyy

WORKDIR /app
COPY Gemfile* .
RUN bundle install

USER hzyy
COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]
