version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    volumes: 
      - db:/data/db
    ports:
      - "27017:27017"

volumes:
  db:
    driver: local
