  FROM ruby:3.1.0
  RUN apt-get update -qq && apt-get install -y postgresql-client

  RUN groupadd -g 1000 hzyy && useradd -u 1000 -g hzyy -m hzyy
  USER hzyy

  WORKDIR /app
  COPY Gemfile* .
  # RUN bundle install

  COPY . .

  # CMD ["rails", "server", "-b", "0.0.0.0"]
